### ISSUE TITLE
Fits fail in 'gaussian_mixture' task

### ISSUE THREAD

**Issue by t1m23** [sbi-benchmark/sbibm#72]
Hi,

I tried running the quickstart code from the github page, for the 'gaussian_linear' task I get reasonable plots (like in the paper). But for the gaussian_mixture task I always get the following:

<img width="1432" alt="gm_task" src="https://github.com/user-attachments/assets/c2baa0d0-9427-4430-9ebe-31565576a840">

I'm using sbibm==1.1.0 and sbi==0.21.0

**Comment by janfb** [comment]
Hi @t1m23 , I am not able to reproduce your error. Can you please share a minimal example? 

My setup is the following: python 3.10, sbibm 1.1.0, sbi 0.21.0

I am using the actual benchmarking API from here: https://github.com/sbi-benchmark/results

Note that I had to change the `requirements.txt` file, requiring `sbibm==1.1.0` instead of `sbibm==1.0.7`. Only then 
Also, I needed to run `pip install future` explicitly before running 

```bash
pip install -r requirements.txt
```

Once this is done, I run

```bash 
python run.py task=gaussian_mixture task.num_simulations=10000 algorithm=rej-abc
```
and it works just fine.

**Comment by janfb** [comment]
Update: I encountered the same error in a different setting. The reason lies in a small bug in the `kde.py` script where the kernel bandwidth is obtained via cross validation (`kde_bandwidth="cv"`): 

https://github.com/sbi-dev/sbi/blob/3ff1f516600e5e56e92ab17b0a13893dfa78f19d/sbi/utils/kde.py#L133-L137

For, the benchmarking script as described above actually finishes, it just shows the `sklearn` error along the way. You can avoid this error by explicitly passing a `kde_bandwidth="scott"`, or `"silverman"` (different KDE kernel heuristics) or a `float`.

**Comment by janfb** [comment]
I will propose a fix in `sbi` itself, but `sbibm` would need to depend on the newest `sbi` then for this to take effect. 

I think there are cases where `scott` is not really a good choice. Another workaround would be to implement and fixed version of the KDE heuristics within `sbibm` and then pass this as explicit float to `sbi`.

**Comment by t1m23** [comment]
Ah okay when I run this command 
'python run.py task=gaussian_mixture task.num_simulations=10000 algorithm=rej-abc'
then it also works for me and I get the results in the 'outputs' folder.

Thanks very much!
